# Basic deployment configuration
replicaCount: 1
nameOverride: ""
fullnameOverride: ""

# Image configuration
image:
  registry: docker.io
  repository: debezium/connect
  tag: "2.5"
  pullPolicy: IfNotPresent
  pullSecrets: []

# Service configuration
service:
  type: ClusterIP
  port: 8083
  annotations: {}

# Kafka Connect configuration
config:
  bootstrapServers: "kafka-controller-0.kafka-controller-headless.${NAMESPACE}.svc.cluster.local:9092"
  groupId: "connect-cluster"
  
  kafka:
    properties:
      # Consumer group configurations
      group.instance.id: "connect-1"
      session.timeout.ms: "45000"
      heartbeat.interval.ms: "15000"
      max.poll.interval.ms: "300000"
      rebalance.timeout.ms: "60000"
      
      # Additional stability settings
      request.timeout.ms: "20000"
      retry.backoff.ms: "500"
      consumer.max.poll.records: "500"
      consumer.max.partition.fetch.bytes: "1048576"
  
  storage:
    config:
      topic: "connect-configs"
      replicationFactor: 1
      partitions: 1
    offset:
      topic: "connect-offsets"
      replicationFactor: 1
      partitions: 25
    status:
      topic: "connect-status"
      replicationFactor: 1
      partitions: 5
  
  consumer:
    max:
      poll:
        interval.ms: "300000"
  producer:
    max:
      request:
        size: "10485760"
    compression:
      type: "snappy"
  offset:
    flush:
      interval.ms: "10000"

# Debezium connectors configuration
connectors: {}

# Resource configuration
resources: {}

# Pod configurations
podAnnotations: {}
podLabels: {}

# Security context
securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Persistence configuration
persistence:
  enabled: true
  size: 8Gi
  storageClass: ""
  accessModes:
    - ReadWriteOnce

# Prometheus metrics
metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    namespace: ""
    interval: "10s"

# Extra volumes and mounts for secrets/configs
extraVolumes: []
extraVolumeMounts: []

# Environment variables
extraEnvVars:
  - name: TZ
    value: "CST6CDT"
extraEnvVarsCM: ""
extraEnvVarsSecret: ""

# Init containers
initContainers: []

# Sidecars
sidecars: []

# Health check
livenessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1